name: Build and Deploy to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Gives the GITHUB_TOKEN the necessary permissions:
permissions:
  contents: read     # Needed to clone code
  pages: write       # Needed to publish Pages
  id-token: write    # Needed for OIDC deployments

# Ensure only one Pages deployment runs at a time
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout your repository
      - uses: actions/checkout@v4

      # 2) Set up Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20  # or another Node version you need
          cache: npm        # speeds up `npm ci` by caching

      # 3) Install dependencies and build
      - run: npm ci
      - run: npm run build

      # 4) Upload your build folder using the *new* artifact action (v4)
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # 1) Download the artifact using the new artifact action (v4)
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./build

      # 2) Configure Pages (ensures your repository is set up for Pages)
      - name: Configure Pages
        uses: actions/configure-pages@v4

      # 3) Deploy to GitHub Pages
      - name: Deploy to Pages
        uses: actions/deploy-pages@v2
        with:
          # By default, this action expects your site files in `./.site`.
          # Instead, we point it to `./build` (the directory we downloaded to).
          artifact: ./build
