name: Build and Deploy to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out your repo
      - uses: actions/checkout@v4

      # 2) Set up Node (pick a version that satisfies your dependencies)
      - uses: actions/setup-node@v4
        with:
          node-version: 20  # or 20, etc.
          cache: npm

      # 3) Install & build
      - run: npm ci
      - run: npm run build

      # 4) Upload your build folder (named "build") as an artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # 1) Download the artifact we uploaded above
      #    and place it into a folder called ".site".
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: .site

      # 2) Configure Pages (sets up the environment for deployment)
      - name: Configure Pages
        uses: actions/configure-pages@v4

      # 3) Deploy
      #    `deploy-pages@v2` automatically deploys
      #    the contents of ".site".
      - name: Deploy to Pages
        uses: actions/deploy-pages@v2
