name: Build and Deploy to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: '16'

      - run: npm ci
      - run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./build

      - uses: actions/configure-pages@v4
        
      - name: Deploy
        uses: actions/deploy-pages@v2
        id: deployment
        with:
          # By default, 'actions/deploy-pages@v2' expects your pages artifact in './.site', 
          # but you can override it with 'artifact: ./build'
          artifact: ./build
